{
    "id": "dbpedia_1794_0",
    "rank": 8,
    "data": {
        "url": "https://stackoverflow.com/questions/77696620/problem-when-checking-connection-with-mongodb",
        "read_more_link": "",
        "language": "en",
        "title": "Problem when checking connection with mongodb",
        "top_image": "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
        "meta_img": "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
        "images": [
            "https://i.sstatic.net/f0gcX.jpg?s=64",
            "https://www.gravatar.com/avatar/819fcf7f531af3b3f2ec488adee441dd?s=64&d=identicon&r=PG&f=y&so-version=2",
            "https://stackoverflow.com/posts/77696620/ivc/324f?prg=369079ca-a31b-4363-a635-a6550d632444"
        ],
        "movies": [],
        "keywords": [],
        "meta_keywords": [
            ""
        ],
        "tags": null,
        "authors": [],
        "publish_date": "2023-12-21T08:25:38",
        "summary": "",
        "meta_description": "from pymongo import MongoClient\n\nclient = MongoClient(host= &quot;localhost&quot;, port= 27017)\nprint(client)\n\nCan anyone help me?\nWhen running these two lines, I get this error:\nRuntimeError: can't",
        "meta_lang": "en",
        "meta_favicon": "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
        "meta_site_name": "Stack Overflow",
        "canonical_link": "https://stackoverflow.com/questions/77696620/problem-when-checking-connection-with-mongodb",
        "text": "from pymongo import MongoClient client = MongoClient(host= \"localhost\", port= 27017) print(client)\n\nCan anyone help me? When running these two lines, I get this error:\n\nRuntimeError: can't create new thread at interpreter shutdown\n\nI asked everyone, they didn't know the problem"
    }
}